views/admin_account_confirm.py
# Logic to generate decode the verification link and find the related user
# While signingup all the details from the user are stored in a temporary table with the status confirmed as false
# A link is generated and is sent to the email provided to check if the email address is real or fake
# User needs to click on the link to verify the account 

from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import url_for
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from utils import application_constant
import itsdangerous
import MySQLdb

#all the query strings used in this file
query1 = "select confirm from Temporary_admin where id = %d"
query2 = "select name,email, password, gender from Temporary_admin where id = %d"
query3 = """ insert into Admin(name, email, password, gender) values("%s","%s","%s","%s") """
query4 = """ update Temporary_admin set confirm = "t" where id = %d """


admin_account_confirm = Blueprint("admin_account_confirm", __name__)

@admin_account_confirm.route("/admin_account_confirm/<token>")
def main(token):
	db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
	cursor = db.cursor()
	s = Serializer("abc", salt = "activate-salt")
	try:
		data = s.loads(token)
		id = data["id"]
		cursor.execute(query1%id) #check the confirm status
		confirm = cursor.fetchone()[0]
		if(confirm == "f"):    # if confirm status is false than store all of the data in Admin table
			cursor.execute(query2%id)
			result = cursor.fetchone()
			name = result[0]
			email = result[1]
			password = result[2]
			gender = result[3]
			cursor.execute(query3%(name,email, password,gender))
			cursor.execute(query4%id) #Update the confirm status as true
			cursor.execute("commit")
			db.close()
			return redirect(url_for("admin_login.main", message = "your account has been verified" ))
		else:
			return redirect(url_for("admin_login.main")) #if the confirm status is true then redirect to the login page
	except itsdangerous.SignatureExpired:
		return redirect(url_for("admin_signup.main", message = "Your verification period has expired please issue a new verification link")) # if the verification period expires then return to the signup page with above message
	cursor.close()
	db.close()

views/admin_add_customer.py
#In this view customer is added by the Admin

from flask import Blueprint
from flask import render_template
from flask import session
from flask import redirect
from flask import url_for
from flask import request
from flask import flash
from flask import jsonify
import MySQLdb
from utils import application_constant
import datetime

#query strings
query = """ insert into Customer(name, email, admin_id, date_of_joining, access) values("%s", "%s",%d, "%s", %d) """

admin_add_customer = Blueprint("admin_add_customer", __name__)
@admin_add_customer.route("/admin_add_customer", methods = ["GET", "POST"])
def main():
	if not session.get("id",0): #if user is not loged in return to home page
		return render_template("zota.html")
	else:
		db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
		cursor = db.cursor()
		if request.method == "GET": #if request method is GET return the admin_add_customer page
			return render_template("admin_add_customer.html")
		else:		#if the request method is post
			name = request.form["name"]
			email = request.form["email"]
			access = 0
			admin_id = session["id"]
			date_time = datetime.datetime.now()	
			f = "%Y-%m-%d %H:%M:%S"
			date_time = date_time.strftime(f)
			try:	#try to insert data into the database
				cursor.execute(query%(name, email, admin_id, date_time, access))
				cursor.execute("commit")
			except: #if it fails then customer all ready existes as email is unique in the Customer table
				message = "Customer already exists"
				db.close()
				return render_template("admin_add_customer.html", message = message) #redirect to admin dashboard
			db.close()
			return render_template("admin_add_customer.html" , message = "Customer Information added") #if value is added to database return to admin_dashboard with a information message
			
			
			

views/admin_dashboard.py
from flask import Blueprint
from flask import url_for
from flask import render_template
from flask import session
from flask import redirect

admin_dashboard = Blueprint("admin_dashboard", __name__)
@admin_dashboard.route("/admin_dashboard")
def main():
	if  session.get("id",0): # if the user is loged in return the dashboard page
		return render_template("admin_dashboard.html")
	else:	#Else redirect to admin login page
		return redirect(url_for("admin_login.main"))

views/admin_login.py
from flask import Blueprint
from flask import render_template
from flask import url_for
from flask import request
from flask import session
from flask import redirect
from utils import application_constant
import MySQLdb

#query string
query = """ select id from Admin where email = "%s" and password = "%s" """

admin_login = Blueprint("admin_login", __name__)
@admin_login.route("/admin_login", methods = ["GET", "POST"])
def main():
	db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
	cursor = db.cursor()
	if session.get("id",0): #check id the user is al ready loged in or not. If yes then go to the admin dashboard
			return redirect(url_for("admin_dashboard.main"))
	if request.method == "GET":  #if the http method is get
		return render_template("admin_login.html") # login page
	else:      #if the http method is post
		email = request.form["email"]
		password = request.form["password"] #select from admin by cross checking together email and password
		cursor.execute(query%(email, password))
		result = cursor.fetchone()
		cursor.close()
		db.close()
		if(result): #if result is not null that means combination exists and user is authenticated
			session["id"] = result[0] #store the id of the admin in session object
			return redirect(url_for("admin_dashboard.main"))
		else:
			return render_template("admin_login.html", message = "Incorrect credentials")
			

views/compose.py
#view logic to send batch mail to the recipients

from flask import Blueprint
from flask import request
from flask import session
from flask import redirect
from flask import url_for
from flask import render_template
from utils import application_constant
import MySQLdb
from customer_send_mail import send_complex_message

query = "select email from Customer where admin_id = %d"

compose = Blueprint("compose", __name__)

@compose.route("/compose", methods = ["GET","POST"])
def main():
	if not session.get("id",0):
		return redirect(url_for("admin_login.main"))
	if request.method == "GET": #if request method is get
		db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
		cursor = db.cursor()
		admin_id = session["id"]
		cursor.execute(query%admin_id) #select all the emails
		emails = cursor.fetchall()
		db.close()
		return render_template("compose.html", emails = emails)
	else:
		recipients = request.form["name"] #recipients string from the client
		subject = request.form["subject"] #subject 
		message = request.form["message"] #body of the mail
		recipients = str(recipients)	  #change unicode string to ascii
		recipients = recipients.split(",") #change comma seperated string to list of email address
		send_complex_message(recipients, subject, message) #Mailgun api to send the batch message
		return render_template("compose.html")

views/customer_individual_information.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import render_template
from utils import application_constant
from customer_send_mail import send_complex_message
import MySQLdb


#query string used in this file
query = "select name, email, date_of_joining from Customer where id = %d"

customer_individual_information = Blueprint("customer_individual_information", __name__)

@customer_individual_information.route("/customer/<int:customer_id>", methods = ["GET", "POST"])
def main(customer_id):
	db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
	cursor = db.cursor()
	if request.method == "GET":  #if the request method is get select all the information and return the individual information 
		cursor.execute(query%customer_id)
		result = cursor.fetchone()
		cursor.close()
		db.close()
		return render_template("customer_individual_information.html", information = result, customer_id = customer_id)
	
	else:
		cursor.execute(query%customer_id)	#if the request method is post
		result = cursor.fetchone()
		cursor.close()
		db.close()
		email = result[1]	#select email id of the customer
		subject = request.form["subject"] #subject of the email
		message = request.form["message"] #body of the email
		send_complex_message(email, subject, message) #send the message using mailgun api
		return render_template("customer_individual_information.html",information = result, customer_id = customer_id)
		
	

views/customer_information.py
#View to fetch all the customer entered admin
#Admin can view the list only it has entered

from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import url_for
import MySQLdb
from flask import session
from utils import application_constant

#query string used in this file
query = """ select id, name, email, date_of_joining from Customer where admin_id = %d """


customer_information = Blueprint("customer_information", __name__)

@customer_information.route("/customer_information")
def main():
	if session.get("id",0): #Checks if the user is loged in or not
		db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
		cursor = db.cursor() 
		cursor.execute(query%session["id"]) #fetch all the result related to customer registered by admin
		result = cursor.fetchall()
		db.close()
		return render_template("customer_information.html", result = result, base_addr = application_constant.BASE_ADDR)
	else:		#if the Admin is not loged in redirect to login page
		return redirect(url_for("admin_login.main"))

views/home.py
from flask import Blueprint
from flask import render_template

home = Blueprint("home", __name__)

@home.route("/")
def main():
	return render_template("zota.html")

views/logout.py
from flask import Blueprint
from flask import redirect
from flask import url_for
from flask import session

logout = Blueprint("logout", __name__)
@logout.route("/logout")
def main():
	if session.get("id",0):
		session.pop("id", None)
		return redirect(url_for("admin_login.main"))

templates/admin_account_confirm.html
<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/dashboard.css') }}">
</head>
<body>
	<p> Hi, {{ name }} </p>
	<p> <a href="{{ url_for('admin_account_confirm.main', token = token, _external = True) }}">Click here to verify your account</a></p>
</body>

templates/admin_add_customer.html
{% extends "dashboard-base.html" %}
{% block right_panel %}
<div class="right-panel">
<div class = "sgp_form">
{% if message %}
<p style="margin-left:20px;margin-top:20px;font-size:30px"> {{ message }} </p>
		{% endif %}
	<form action="{{ url_for('admin_add_customer.main') }}" method = "POST">
	<input type = "text" placeholder = "Name" name = "name" required><br>
	<input type = "email" placeholder = "Email" name = "email" required><br>
	<input type = "submit" value = "SUBMIT">
</form>
</div>
</div>
{% endblock %}

templates/admin_dashboard.html
{% extends "dashboard-base.html" %}

{% block right_panel %}
	<div class="right-panel">
		{% if message %}
			<p style="margin-left:200px;margin-top:200px;font-size:30px"> {{ message }} </p>
		{% endif %}
	</div>
{% endblock %}

templates/admin_login.html
<!DOCTYPE html>
<head>
	<title>Zota|User|Signup</title>
	<meta charset="UTF-8">

	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/login_signup.css') }}">
</head>
<body>
	 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
     <li><a class="navbar-brand" href='{{url_for("home.main") }}' style="font-size:20px;">Zota Technologies</a></a></li>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href='{{url_for("admin_signup.main") }}'><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li class="active"><a href='{{url_for("admin_login.main") }}'><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<div class="sgp_form">
  {% if message %}
      {{ message }}
  {% endif %}
    <form method = "POST" action = "">
      <input type="email" placeholder="Email" name="email" required><br>
      <input type="password" placeholder="Password" name="password" required><br>
      <input type="submit" value="Login">
    </form>
</div>
</body>

templates/compose.html
{% extends "dashboard-base.html" %}
{% block right_panel %}
<div class = "right-panel" style = "padding-left:20vw;">
<div ng-app="EmailList" ng-cloak ng-controller="myCtrl" class="w3-card-2 w3-margin" style="max-width:400px;">
  <header>
    <h3>Recipient List</h3>
  </header>
  <ul class="w3-ul">
    <li ng-repeat="x in products" class="w3-padding-16">{{ '{{x}}' }}<span ng-click="removeItem($index)" style="cursor:pointer;" class="w3-right w3-margin-right">×</span></li>
  </ul>
  <div>
    <div class="w3-row w3-margin-top">
      <div class="w3-col s10">
        <input list="emailid" placeholder="Add Email here" ng-model="addMe" class="w3-input w3-border w3-padding">
      <datalist id="emailid">
      {% for email in emails %}
       <option value="{{ email[0] }}">
      {% endfor %}
      </datalist>
      </div>
      <div class="w3-col s2">
        <button ng-click="addItem()" class="w3-btn w3-padding w3-green">Add</button>
      </div>
    </div>
    <p class="w3-padding-left w3-text-red">{{ '{{errortext}}' }}</p>
     <p class="w3-padding-left w3-text-red">{{ '{{ message_sent }}' }}</p>
  </div>
  <form>
    <input type="text" Placeholder = "Subject" ng-model = "subject">
    <textarea type="text" ng-model="message">
    </textarea>
  </form>
  <button ng-click="myFunction()">Click me!</button><br>
</div>
</div>
<script type="text/javascript" src = "{{url_for('static', filename='js/compose.js') }}"></script>

{% endblock %}

templates/customer_individual_information.html
{% extends "dashboard-base.html" %}
{% block right_panel %}
<div class="right-panel">
	<table class="table table-hover">
    <tr>
    	<th>Name</th>
    	<td>{{ information[0] }}</td>
    </tr>
    <tr>
    	<th>Email</th>
    	<td>{{ information[1] }}</td>
    </tr>
    <tr>
    	<th>Date Joined</th>
    	<td>{{ information[2] }}</td>
    </tr>
  </table>
 <div style="margin-left:200px;margin-top:80px;">
<form action="{{ url_for('customer_individual_information.main', customer_id =  customer_id ) }}" method = "POST">
<input type="text" placeholder = "Subject" name = "subject" required><br>
 <textarea rows="10" cols="60" name = "message" required>
 </textarea><br>
 <input type="submit" value = "SUBMIT">
</form>
</div>
</div>
{% endblock %}

templates/customer_information.html
	{% extends "dashboard-base.html" %}
  {% block right_panel %}
  <div class="right-panel">
    <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Date Joined</th>
      </tr>
    </thead>
    <tbody>
  {% for information in result %}
      <tr onClick = "window.document.location = '{{ base_addr }}/customer/{{ information[0] }}' ">
        <td>{{ information[1] }}</td>
        <td>{{ information[2] }}</td>
        <td>{{ information[3] }}</td>
      </tr>
  {% endfor %}
    </tbody>
  </table>
  </div>
  {% endblock %}

templates/dashboard-base.html
<!DOCTYPE html>
<head>
	<title>Zota|Admin|Dashboard</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/dashboard.css') }}">
	<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<body>

</head>
<body>
	<div class="left-panel">
		<div class = "left-panel-menu">
		<a href= '{{ url_for("home.main") }}'><h1 style="font-size:55px;color:white;margin-left:40px;">Zota</h1></a>
		<hr>
		<a href="{{ url_for('admin_add_customer.main') }}" id="enter-customer">Enter Customer</a> <br>
		<hr>
		<a href="{{ url_for('customer_information.main') }}" id="customer-information">Cutomer Details</a> <br>
		<hr>
		<a href="{{ url_for('compose.main') }}">Compose</a>
		<hr>
		<a href="{{ url_for('logout.main') }}">Logout</a>
		<hr>
	    </div>
	</div>
	{% block right_panel %}
	{% endblock %}
</body>

templates/signup.html
<!DOCTYPE html>
<head>
	<title>Zota|User|Signup</title>
	<meta charset="UTF-8">

	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/login_signup.css') }}">
</head>
<body>
	  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
     <li><a class="navbar-brand" href='{{url_for("home.main") }}' style="font-size:20px;">Zota Technologies</a></a></li>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href='{{url_for("admin_signup.main") }}'><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href='{{url_for("admin_login.main") }}'><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<div class="sgp_form">
  {% if message %}
      {{ message }}
  {% endif %}
    <form method = "POST" action = "">
      <input type="text" placeholder="Name" name="name" required><br>
      <input type="email" placeholder="Email" name="email" required><br>
      <input type="password" placeholder="Password" name="password" required><br>
      <label style="margin-right:20px;">Gender</label>
      <input type="radio" name="gender" value="m" checked> Male
      <input type="radio" name="gender" value="f" style="margin-left:60px;"> Female<br>
      <input type="submit" value="Signup">
    </form>
</div>
</body>

templates/zota.html
<!DOCTYPE html>
<head>
	<title>Zota</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/login_signup.css') }}">
</head>
<body>
	 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
     <li class="active"><a class="navbar-brand" href='{{url_for("home.main") }}' style="font-size:20px;">Zota Technologies</a></a></li>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href='{{url_for("admin_signup.main") }}'><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href='{{url_for("admin_login.main") }}'><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<div>
  <h1 style="font-size:245px;margin-left:50vw;margin-top:50vh;color:white;">Zota</h1>
</div>
</body>